#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

refine()
{
    runApplication -s $1 \
        topoSet -dict system/topoSetDict.${1}

    runApplication -s $1 \
        refineMesh -dict system/refineMeshDict -overwrite
}

runApplication blockMesh

for i in 1 2 3 4
do
    refine $i
done

runApplication setFields
runApplication porousFieldSimpleFoam
